from.annual_overview import AnnualOverview
from.attachment_public import AttachmentPublic
from.attachment_tab import AttachmentTab
from.avatar import Avatar
from.customer_statement import CustomerStatement
from.draft_share_invite_bank import DraftShareInviteBank
from.share_invite_bank_inquiry import ShareInviteBankInquiry
from.share_invite_bank_response import ShareInviteBankResponse
from.card import Card
from.cash_register import CashRegister
from.certificate_pinned import CertificatePinned
from.chat_conversation import ChatConversation
from.draft_payment import DraftPayment
from.invoice import Invoice
from.master_card_action import MasterCardAction
from.monetary_account import MonetaryAccount
from.payment import Payment
from.request_inquiry import RequestInquiry
from.schedule import Schedule
from.scheduled_payment import ScheduledPayment
from.tab import Tab
from.user import User


class Controller:

    def __init__(self, api_client):
        self.api_client = api_client
        self.user = User(api_client)
        self.monetary_account = MonetaryAccount(api_client)
        self.card = Card(api_client)
        self.payment = Payment(api_client)
        self.request_inquiry = RequestInquiry(api_client)
        self.draft_payment = DraftPayment(api_client)
        self.schedule = Schedule(api_client)
        self.scheduled_payment = ScheduledPayment(api_client)
        self.cash_register = CashRegister(api_client)
        self.master_card_action = MasterCardAction(api_client)
        self.chat_conversation = ChatConversation(api_client)
        self.certificate_pinned = CertificatePinned(api_client)
        self.invoice = Invoice(api_client)
        self.annual_overview = AnnualOverview(api_client)
        self.attachment_public = AttachmentPublic(api_client)
        self.attachment_tab = AttachmentTab(api_client)
        self.avatar = Avatar(api_client)
        self.customer_statement = CustomerStatement(api_client)
        self.draft_invite = DraftShareInviteBank(api_client)
        self.share_inquiry = ShareInviteBankInquiry(api_client)
        self.share_response = ShareInviteBankResponse(api_client)
        self.tab = Tab(api_client)
